# Generated by Django 2.0.5 on 2018-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20180911_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypeuploads',
            name='issues',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='genotypeuploads',
            name='upload_fail',
            field=models.FileField(blank=True, upload_to='logs/'),
        ),
        migrations.AlterField(
            model_name='genotypeuploads',
            name='upload_pass',
            field=models.FileField(blank=True, upload_to='logs/'),
        ),
    ]
