# Generated by Django 2.0.5 on 2018-08-07 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20180806_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotypes',
            fields=[
                ('parent_f_row', models.CharField(max_length=200)),
                ('parent_m_row', models.CharField(max_length=200)),
                ('parent_f_geno', models.CharField(max_length=200)),
                ('parent_m_geno', models.CharField(max_length=200)),
                ('genotype', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('seed_count', models.IntegerField(default=0)),
                ('actual_count', models.BooleanField()),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('tissue_comments', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid', message='Needs to start with WOW', regex='^WOW')]),
        ),
    ]
