# Generated by Django 2.0.5 on 2018-09-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20180911_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypeuploads',
            name='issues',
            field=models.IntegerField(default=0),
        ),
    ]
