# Generated by Django 2.0.5 on 2018-08-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20180807_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genotypes',
        ),
    ]
