# Generated by Django 2.0.5 on 2018-09-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20180911_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypeuploads',
            name='issues',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
