# Generated by Django 2.0.5 on 2018-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_delete_genotypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_f_row', models.CharField(max_length=200)),
                ('parent_m_row', models.CharField(max_length=200)),
                ('parent_f_geno', models.CharField(max_length=200)),
                ('parent_m_geno', models.CharField(max_length=200)),
                ('genotype', models.CharField(max_length=200)),
                ('seed_count', models.IntegerField(default=0)),
                ('actual_count', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('tissue_comments', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
