# Generated by Django 2.0.5 on 2018-08-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_genotypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genotypes',
        ),
    ]
