# Generated by Django 2.0.5 on 2018-08-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_genotypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genotypes',
            options={'verbose_name_plural': 'Genotypes'},
        ),
    ]
